from config.core import REF_HEIGHT, REF_WIDTH, SCREEN_WIDTH, BLACK, WHITE, SCREEN_HEIGHT

GAME_BG_COLOR = BLACK

# Button configuration
BUTTON_TEXT_FONT_SIZE = int(SCREEN_HEIGHT * (32 / REF_HEIGHT))
BUTTON_TEXT_COLOR = WHITE
BUTTON_TEXT_WRAP_WIDTH = int(SCREEN_WIDTH * (300 / REF_WIDTH))
BUTTON_TEXT_ALIGN = "center"
BUTTON_DIAMETER = int(SCREEN_WIDTH * (120 / REF_WIDTH))

LEFT_BUTTON_X = int((SCREEN_WIDTH - BUTTON_DIAMETER) // 2 - (150 / REF_WIDTH) * SCREEN_WIDTH)
LEFT_BUTTON_Y = int((SCREEN_HEIGHT - BUTTON_DIAMETER) // 2 + (350 / REF_HEIGHT) * SCREEN_HEIGHT)

RIGHT_BUTTON_X = int((SCREEN_WIDTH - BUTTON_DIAMETER) // 2 + (150 / REF_WIDTH) * SCREEN_WIDTH)
RIGHT_BUTTON_Y = int((SCREEN_HEIGHT - BUTTON_DIAMETER) // 2 + (350 / REF_HEIGHT) * SCREEN_HEIGHT)

TOP_BUTTON_X = int((SCREEN_WIDTH - BUTTON_DIAMETER) // 2)
TOP_BUTTON_Y = int((SCREEN_HEIGHT - BUTTON_DIAMETER) // 2 + (100 / REF_HEIGHT) * SCREEN_HEIGHT)

# Question text configuration
QUESTION_TEXT_FONT_SIZE = int(SCREEN_HEIGHT * (70 / REF_HEIGHT))
QUESTION_TEXT_WRAP_WIDTH = int(SCREEN_WIDTH * 0.75)
QUESTION_TEXT_X = (SCREEN_WIDTH - QUESTION_TEXT_WRAP_WIDTH) // 2
QUESTION_TEXT_Y = int((200 / REF_HEIGHT) * SCREEN_HEIGHT)
QUESTION_TEXT_ALIGN = "center"

# Sprite configuration
ROV_IMAGE = "assets/sprites/ROV.png"
ROV_X = SCREEN_WIDTH * (0.7)
ROV_Y = SCREEN_HEIGHT * (0.5)
ROV_ROTATION = 0
ROV_WIDTH = int(SCREEN_WIDTH * (220 / REF_WIDTH))

SHEARS_IMAGE = "assets/sprites/shears.png"
SHEARS_X = SCREEN_WIDTH * (0.61)
SHEARS_Y = SCREEN_HEIGHT * (0.58)
SHEARS_ROTATION = 0
SHEARS_WIDTH = int(SCREEN_WIDTH * (150 / REF_WIDTH))

TEXT_BUBBLE_IMAGE = "assets/sprites/Copy of When do you want to start the mission-2.png"
TEXT_BUBBLE_X = SCREEN_WIDTH * (0.77)
TEXT_BUBBLE_Y = SCREEN_HEIGHT * (0.33)
TEXT_BUBBLE_ROTATION = 0
TEXT_BUBBLE_WIDTH = int(SCREEN_WIDTH * (300 / REF_WIDTH))

BUOY_IMAGE = "assets/sprites/Buoy for Ghost Gear Removal Mission.png"
BUOY_X = SCREEN_WIDTH * (0.3)
BUOY_Y = SCREEN_HEIGHT * (0.6)
BUOY_ROTATION = 0
BUOY_WIDTH = int(SCREEN_WIDTH * (100 / REF_WIDTH))