from config.core import SCREEN_WIDTH, BLACK, WHITE, SCREEN_HEIGHT

GAME_BG_COLOR = BLACK

# Button configuration
BUTTON_TEXT_FONT_SIZE = 24
BUTTON_TEXT_COLOR = WHITE
BUTTON_DIAMETER = 120
LEFT_BUTTON_X = (SCREEN_WIDTH - BUTTON_DIAMETER) // 2 - 150
LEFT_BUTTON_Y = (SCREEN_HEIGHT - BUTTON_DIAMETER) // 2 + 200
RIGHT_BUTTON_X = (SCREEN_WIDTH - BUTTON_DIAMETER) // 2 + 150
RIGHT_BUTTON_Y = (SCREEN_HEIGHT - BUTTON_DIAMETER) // 2 + 200
TOP_BUTTON_X = (SCREEN_WIDTH - BUTTON_DIAMETER) // 2
TOP_BUTTON_Y = (SCREEN_HEIGHT - BUTTON_DIAMETER) // 2 - 50

# Question text configuration
QUESTION_TEXT_X = (SCREEN_WIDTH // 2) - 200
QUESTION_TEXT_Y = 200
QUESTION_TEXT_FONT_SIZE = 64

# Sprite configuration
FISH_X = 200
FISH_Y = (SCREEN_HEIGHT // 2) - 100
FISH_IMAGE = "assets/sprites/fish-lossy607.jp2.png"
FISH_WIDTH = 200
FISH_ROTATION = 45
