from config.core import SCREEN_WIDTH, BLACK, WHITE, SCREEN_HEIGHT

GAME_BG_COLOR = BLACK

# Button configuration
BUTTON_TEXT_FONT_SIZE = 32
BUTTON_TEXT_COLOR = WHITE
BUTTON_TEXT_WRAP_WIDTH = 300
BUTTON_TEXT_ALIGN = "center"
BUTTON_DIAMETER = 120
LEFT_BUTTON_X = (SCREEN_WIDTH - BUTTON_DIAMETER) // 2 - 150
LEFT_BUTTON_Y = (SCREEN_HEIGHT - BUTTON_DIAMETER) // 2 + 350
RIGHT_BUTTON_X = (SCREEN_WIDTH - BUTTON_DIAMETER) // 2 + 150
RIGHT_BUTTON_Y = (SCREEN_HEIGHT - BUTTON_DIAMETER) // 2 + 350
TOP_BUTTON_X = (SCREEN_WIDTH - BUTTON_DIAMETER) // 2
TOP_BUTTON_Y = (SCREEN_HEIGHT - BUTTON_DIAMETER) // 2 + 100

# Question text configuration
QUESTION_TEXT_FONT_SIZE = 70
QUESTION_TEXT_WRAP_WIDTH = int(SCREEN_WIDTH * 0.75)
QUESTION_TEXT_X = (SCREEN_WIDTH - QUESTION_TEXT_WRAP_WIDTH) // 2
QUESTION_TEXT_Y = 200
QUESTION_TEXT_ALIGN = "center"

# Sprite configuration
