from config.core import DEFAULT_TEXT_WIDTH, WHITE, BLACK, SCREEN_WIDTH, SCREEN_HEIGHT

START_BG_COLOR = BLACK
START_TEXT_COLOR = (193, 255, 114)
START_FONT_SIZE = 48

# Button configuration
START_BUTTON_TEXT = "Press to Start"
START_BUTTON_TEXT_COLOR = WHITE
START_BUTTON_DIAMETER = 120
START_BUTTON_X = (SCREEN_WIDTH - START_BUTTON_DIAMETER) // 2
START_BUTTON_Y = SCREEN_HEIGHT - START_BUTTON_DIAMETER - 300
START_BUTTON_TEXT_MARGIN = 100

# Text configuration
TITLE_BOX_WIDTH = int(SCREEN_WIDTH * 0.75)
TITLE_TEXT_X = (SCREEN_WIDTH - TITLE_BOX_WIDTH) // 2
TITLE_TEXT_Y = 200
TITLE_TEXT_FONT_SIZE = 90
TITLE_TEXT = "Ghost Gear Removal"
TITLE_TEXT_WRAP_WIDTH = TITLE_BOX_WIDTH
TITLE_TEXT_ALIGN = "center"

# Sprite configuration
BACKGROUND_IMAGE = "assets/sprites/Ship with Back background.png"
BACKGROUND_OFFSET_X = 235