from config.core import DEFAULT_TEXT_WIDTH, WHITE, BLACK, SCREEN_WIDTH, SCREEN_HEIGHT

START_BG_COLOR = BLACK
START_TEXT = "Press any key to start"
START_TEXT_COLOR = WHITE
START_FONT_SIZE = 48

# Button configuration
START_BUTTON_TEXT = ""
START_BUTTON_TEXT_COLOR = WHITE
START_BUTTON_DIAMETER = 120
START_BUTTON_X = (SCREEN_WIDTH - START_BUTTON_DIAMETER) // 2
START_BUTTON_Y = SCREEN_HEIGHT - START_BUTTON_DIAMETER - 300

# Text configuration
TITLE_TEXT_X = (SCREEN_WIDTH // 2) - (DEFAULT_TEXT_WIDTH // 2)
TITLE_TEXT_Y = 200
TITLE_TEXT_FONT_SIZE = 64
TITLE_TEXT = "Ghost Gear Removal"
