from config.core import REF_HEIGHT, REF_WIDTH, WHITE, BLACK, SCREEN_WIDTH, SCREEN_HEIGHT

START_BG_COLOR = BLACK
START_TEXT_COLOR = (193, 255, 114)

# Fonts (scale by height)
START_FONT_SIZE = int(SCREEN_HEIGHT * (48 / REF_HEIGHT))

# Button configuration (scale by width for diameters, and by width/height for position offsets)
START_BUTTON_TEXT = "Press to Start"
START_BUTTON_TEXT_COLOR = WHITE
START_BUTTON_DIAMETER = int(SCREEN_WIDTH * (120 / REF_WIDTH))
START_BUTTON_X = (SCREEN_WIDTH - START_BUTTON_DIAMETER) // 2
START_BUTTON_Y = int(SCREEN_HEIGHT - START_BUTTON_DIAMETER - (300 / REF_HEIGHT) * SCREEN_HEIGHT)
START_BUTTON_TEXT_MARGIN = int(SCREEN_HEIGHT * (100 / REF_HEIGHT))

# Text configuration
TITLE_BOX_WIDTH = int(SCREEN_WIDTH * 0.75)
TITLE_TEXT_X = (SCREEN_WIDTH - TITLE_BOX_WIDTH) // 2
TITLE_TEXT_Y = int((200 / REF_HEIGHT) * SCREEN_HEIGHT)
TITLE_TEXT_FONT_SIZE = int(SCREEN_HEIGHT * (90 / REF_HEIGHT))
TITLE_TEXT = "Ghost Gear Removal"
TITLE_TEXT_WRAP_WIDTH = TITLE_BOX_WIDTH
TITLE_TEXT_ALIGN = "center"

# Sprite configuration
BACKGROUND_IMAGE = "assets/sprites/Ship with Back background.png"
BACKGROUND_OFFSET_X = int((235 / REF_WIDTH) * SCREEN_WIDTH)
